; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[] = "drupal"
; Modules
projects[views_bulk_operations][subdir] = "contrib"

projects[admin_menu][subdir] = "contrib"

projects[admin_views][subdir] = "contrib"

projects[ctools][subdir] = "contrib"

projects[ckeditor][subdir] = "contrib"

projects[date][subdir] = "contrib"

projects[devel][subdir] = "contrib"

projects[entity][subdir] = "contrib"

projects[entityreference][subdir] = "contrib"

projects[features][subdir] = "contrib"

projects[jquery_update][subdir] = "contrib"

projects[logintoboggan][subdir] = "contrib"

projects[module_filter][subdir] = "contrib"

projects[pathauto][subdir] = "contrib"

projects[rules][subdir] = "contrib"

projects[strongarm][subdir] = "contrib"

projects[token][subdir] = "contrib"

projects[views][subdir] = "contrib"

; Themes
projects[bootstrap][version] = "3.x-dev"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[b3_camp][download][type] = ""
projects[b3_camp][download][url] = ""
projects[b3_camp][type] = "theme"

